//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Microsoft.WindowsAzure.Management.ServiceManagement.Extensions.DomainJoin {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PublicConfig {
        
        private Name nameField;
        
        private string userField;
        
        private string localUserField;
        
        private string newNameField;
        
        private PublicConfigOptions optionsField;
        
        private string oUPathField;
        
        private bool restartField;
        
        private bool restartFieldSpecified;
        
        private string serverField;
        
        private string unjoinDomainUserField;
        
        private bool unsecureField;
        
        private bool unsecureFieldSpecified;
        
        /// <remarks/>
        public Name Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string LocalUser {
            get {
                return this.localUserField;
            }
            set {
                this.localUserField = value;
            }
        }
        
        /// <remarks/>
        public string NewName {
            get {
                return this.newNameField;
            }
            set {
                this.newNameField = value;
            }
        }
        
        /// <remarks/>
        public PublicConfigOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        public string OUPath {
            get {
                return this.oUPathField;
            }
            set {
                this.oUPathField = value;
            }
        }
        
        /// <remarks/>
        public bool Restart {
            get {
                return this.restartField;
            }
            set {
                this.restartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RestartSpecified {
            get {
                return this.restartFieldSpecified;
            }
            set {
                this.restartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        public string UnjoinDomainUser {
            get {
                return this.unjoinDomainUserField;
            }
            set {
                this.unjoinDomainUserField = value;
            }
        }
        
        /// <remarks/>
        public bool Unsecure {
            get {
                return this.unsecureField;
            }
            set {
                this.unsecureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnsecureSpecified {
            get {
                return this.unsecureFieldSpecified;
            }
            set {
                this.unsecureFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Name {
        
        private NameType typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NameType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum NameType {
        
        /// <remarks/>
        Domain,
        
        /// <remarks/>
        Workgroup,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PublicConfigOptions {
        
        private JoinOptions[] optionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Option")]
        public JoinOptions[] Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum JoinOptions {
        
        /// <remarks/>
        AccountCreate,
        
        /// <remarks/>
        Win9XUpgrade,
        
        /// <remarks/>
        UnsecuredJoin,
        
        /// <remarks/>
        PasswordPass,
        
        /// <remarks/>
        JoinWithNewName,
        
        /// <remarks/>
        JoinReadOnly,
        
        /// <remarks/>
        InstallInvoke,
    }
}
